// Curated PULS legal-owner -> map brand mappings.
// These aliases do not overwrite PULS Owner; they only set responsibleBrandId.
Object.assign(OWNER_ALIASES_RAW, {
  "lolland spildevand": "lolland-forsyning",
  "sk spildevand": "envafors",
  "tønder spildevand": "toender-forsyning",
  "guldborgsund spildevand": "guldborgsund-forsyning",
  "vordingborg spildevand": "vordingborg-forsyning",
  "herning rens": "herning-vand",
  "fors spildevand holbæk": "fors",
  "fors spildevand lejre": "fors",
  "fors spildevand roskilde": "fors",
  "rebild vand og spildevand": "rebild-forsyning",
  "odsherred spildevand": "odsherred-forsyning",
  "kalundborg renseanlæg": "kalundborg-forsyning",
  "frederikshavn spildevand": "frederikshavn-forsyning",
  "langeland spildevand": "langeland-forsyning",
  "silkeborg spildevand": "silkeborg-forsyning",
  "ffv spildevand": "ffv",
  "nk spildevand": "envafors",
  "bornholms spildevand": "beof",
  "arwos spildevand": "arwos",
  "halsnæs spildevand": "halsnaes-forsyning",
  "svendborg spildevand": "vand-og-affald",
  "assens rensning": "assens-forsyning",
  "favrskov spildevand": "favrskov-forsyning",
  "skanderborg spildevand": "skanderborg-forsyning",
  "thy renseanlæg": "thisted-vand",
  "faxe spildevandscenter": "faxe-forsyning",
  "sorø spildevand": "envafors",
  "hillerød spildevand": "hilleroed-forsyning",
  "stevns spildevand": "klar-forsyning",
  "køge afløb": "klar-forsyning",
  "solrød spildevand": "klar-forsyning",
  "greve spildevand": "klar-forsyning",
  "nfs spildevand": "nyborg-forsyning",
  "billund spildevand": "billund-vand-energi",
  "grindsted renseanlæg": "billund-vand-energi",
  "ærø vand": "aeroe-forsyning",
  "odder spildevand": "samn-forsyning",
  "horsens vand": "samn-forsyning",
  "fredensborg spildevand": "fredensborg-forsyning",
  "morsø spildevand": "morsoe-forsyning",
  "ringsted spildevand": "ringsted-forsyning",
  "brønderslev spildevand": "broenderslev-forsyning",
  "struer forsyning spildevand": "struer-energi",
  "gribvand": "gribskov-forsyning",
  "aalborg kloak": "aalborg-forsyning",
  "læsø vand": "laesoe-forsyning",
  "hofor spildevand dragør": "hofor",
  "tårnbyforsyning spildevand": "taarnby-forsyning",
  "htk kloak": "htk-forsyning"
});
