function renderDrawer(){
  const ws=view==='templates'&&templateEditorId?activeTemplate():activeTrip();
  const inWs=new Set((ws?.items||[]).map(i=>i.gearId));
  const q=gearQuery.trim().toLowerCase();
  let gear=state.gear.filter(g=>!g.archived).filter(g=>!q||`${g.name} ${g.description}`.toLowerCase().includes(q));
  if(gearCategoryFilter!=='all') gear=gear.filter(g=>g.defaultCategory===gearCategoryFilter);
  if(gearStorageFilter!=='all') gear=gear.filter(g=>gearStorageFilter==='unassigned'?!g.storageId:g.storageId===gearStorageFilter);
  const groups=new Map();
  for(const g of gear){ const key=g.storageId||'unassigned'; if(!groups.has(key)) groups.set(key,[]); groups.get(key).push(g); }
  const ordered=[...groups.entries()].sort((a,b)=>{
    if(a[0]==='unassigned') return -1; if(b[0]==='unassigned') return 1; return storagePath(a[0]).localeCompare(storagePath(b[0]),'da');
  });
  return `<div class="drawer-backdrop ${drawerOpen?'open':''}" data-action="close-gear"></div><aside class="drawer ${drawerOpen?'open':''}"><div class="drawer-head"><div><div class="drawer-title">Gear Pool</div><div class="panel-sub">Drag individuelt til pakkelisten</div></div><button class="btn small" data-action="close-gear">✕</button></div><div class="drawer-filters"><input class="input" id="gear-search-drawer" placeholder="Søg gear…" value="${esc(gearQuery)}"><div class="searchbar"><select class="input" id="gear-category-drawer"><option value="all">Alle kategorier</option>${DEFAULT_CATEGORIES.map(c=>`<option value="${esc(c)}" ${gearCategoryFilter===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select class="input" id="gear-storage-drawer"><option value="all">Alle storage</option><option value="unassigned" ${gearStorageFilter==='unassigned'?'selected':''}>Unassigned</option>${state.storage.map(s=>`<option value="${s.id}" ${gearStorageFilter===s.id?'selected':''}>${esc(storageLabel(s))}</option>`).join('')}</select></div></div><div class="drawer-body">${!ws?`<div class="storage-empty">Opret eller vælg først en trip.</div>`:ordered.map(([key,arr])=>`<div class="gear-group"><div class="group-head"><span>${esc(key==='unassigned'?'Unassigned':storagePath(key))}</span><span>${arr.length}</span></div>${arr.map(g=>`<div class="pool-item ${inWs.has(g.id)?'in-trip':''}" draggable="${!inWs.has(g.id)}" data-pool-gear="${g.id}"><span class="drag-handle">⋮⋮</span><div class="pool-main"><div class="pool-name">${esc(g.name)}</div><div class="pool-desc">${esc(g.description||g.defaultCategory)}</div></div><span class="pool-weight">${fmtWeight(g.weight)}</span><button class="add-circle" data-action="add-gear-default" data-gear="${g.id}" title="${inWs.has(g.id)?'Allerede på listen':'Tilføj'}">${inWs.has(g.id)?'✓':'＋'}</button></div>`).join('')}</div>`).join('')}</div></aside>`;
}

function renderModal(){
  if(!modal) return '';
  const close=`<button class="btn small" data-action="close-modal">✕</button>`;
  if(modal.type==='new-trip'){
    return modalShell('Ny tur',close,`<form id="new-trip-form"><div class="form-grid"><div class="field full"><label class="label">Navn</label><input class="input" name="name" placeholder="Fx West Highland Way 2027" required autofocus></div><div class="field"><label class="label">Dato</label><input class="input" name="date" type="date"></div><div class="field"><label class="label">Startpunkt</label><select class="input" name="template"><option value="empty">Tom liste</option>${state.templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}<option value="copy">Kopiér nuværende trip</option></select></div></div><div class="modal-actions"><button type="button" class="btn" data-action="close-modal">Annullér</button><button class="btn primary">Opret tur</button></div></form>`);
  }
  if(modal.type==='edit-trip'){
    const t=activeTrip();
    return modalShell('Redigér tur',close,`<form id="edit-trip-form"><div class="form-grid"><div class="field full"><label class="label">Navn</label><input class="input" name="name" value="${esc(t.name)}" required></div><div class="field"><label class="label">Dato</label><input class="input" name="date" type="date" value="${esc(t.date||'')}"></div></div><div class="modal-actions"><button type="button" class="btn danger" data-action="delete-trip">Slet tur</button><button class="btn primary">Gem</button></div></form>`);
  }
  if(modal.type==='gear'){
    const g=modal.gearId?gearById(modal.gearId):null;
    return modalShell(g?'Redigér gear':'Nyt gear',close,`<form id="gear-form"><input type="hidden" name="id" value="${esc(g?.id||'')}"><div class="form-grid"><div class="field full"><label class="label">Navn</label><input class="input" name="name" value="${esc(g?.name||'')}" required></div><div class="field"><label class="label">Vægt (g)</label><input class="input" name="weight" type="number" min="0" step="1" value="${g?.weight??0}" required></div><div class="field"><label class="label">Default trip category</label><select class="input" name="category">${DEFAULT_CATEGORIES.map(c=>`<option ${g?.defaultCategory===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field full"><label class="label">Model / beskrivelse</label><input class="input" name="description" value="${esc(g?.description||'')}"></div><div class="field full"><label class="label">Storage</label><select class="input" name="storage"><option value="">Unassigned</option>${state.storage.map(s=>`<option value="${s.id}" ${g?.storageId===s.id?'selected':''}>${esc(storagePath(s.id))}</option>`).join('')}</select></div><div class="field full"><label class="label">Noter</label><textarea class="input" name="notes">${esc(g?.notes||'')}</textarea></div></div><div class="modal-actions">${g?`<button type="button" class="btn danger" data-action="archive-gear" data-gear="${g.id}">Arkivér</button>`:''}<button class="btn primary">Gem</button></div></form>`);
  }
  if(modal.type==='workspace-item'){
    const ws=view==='templates'&&templateEditorId?activeTemplate():activeTrip();
    const item=ws?.items.find(i=>i.id===modal.itemId), g=item?gearById(item.gearId):null;
    if(!item||!g) return '';
    return modalShell(g.name,close,`<form id="workspace-item-form"><input type="hidden" name="id" value="${item.id}"><div class="form-grid"><div class="field full"><label class="label">Kategori</label><select class="input" name="category">${(ws.categories||DEFAULT_CATEGORIES).map(c=>`<option ${item.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="field full"><label class="label">Status</label><div class="check-grid"><button type="button" class="toggle-pill ${item.worn?'active':''}" data-toggle="worn">Worn</button><button type="button" class="toggle-pill ${item.consumable?'active':''}" data-toggle="consumable">Consumable</button></div><input type="hidden" name="worn" value="${item.worn?'1':'0'}"><input type="hidden" name="consumable" value="${item.consumable?'1':'0'}"></div><div class="field full"><label class="label">Trip note</label><textarea class="input" name="notes">${esc(item.notes||'')}</textarea></div><div class="field full"><label class="label">Storage</label><div class="input" style="background:var(--surface-2)">${esc(storagePath(g.storageId))}</div></div></div><div class="modal-actions"><button type="button" class="btn danger" data-action="remove-workspace-item" data-item="${item.id}">Fjern fra listen</button><button class="btn primary">Gem</button></div></form>`);
  }
  if(modal.type==='storage'){
    const s=modal.storageId?storageById(modal.storageId):null; const suggested=s?.type==='box'?s.number:nextBoxNumber();
    return modalShell(s?'Redigér storage':'Ny storage',close,`<form id="storage-form"><input type="hidden" name="id" value="${esc(s?.id||'')}"><div class="form-grid"><div class="field"><label class="label">Type</label><select class="input" name="type" id="storage-type"><option value="location" ${s?.type==='location'?'selected':''}>Location</option><option value="shelf" ${s?.type==='shelf'?'selected':''}>Reol</option><option value="box" ${s?.type==='box'?'selected':''}>Box</option></select></div><div class="field"><label class="label">Parent</label><select class="input" name="parent"><option value="">Top level</option>${state.storage.filter(x=>x.id!==s?.id).map(x=>`<option value="${x.id}" ${s?.parentId===x.id?'selected':''}>${esc(storagePath(x.id))}</option>`).join('')}</select></div><div class="field full storage-name-field"><label class="label">Navn / beskrivelse</label><input class="input" name="name" value="${esc(s?.name||'')}" placeholder="Fx Reol ved døren eller Cooking + Water"></div><div class="field storage-number-field ${s?.type==='box'?'':'hidden'}"><label class="label">Box-nummer</label><input class="input" name="number" type="number" min="1" step="1" value="${suggested}"></div></div><div class="modal-actions">${s?`<button type="button" class="btn danger" data-action="delete-storage" data-storage="${s.id}">Slet</button>`:''}<button class="btn primary">Gem</button></div></form>`);
  }
  if(modal.type==='template-meta'){
    const t=modal.templateId?state.templates.find(x=>x.id===modal.templateId):null;
    return modalShell(t?'Redigér template':'Ny template',close,`<form id="template-form"><input type="hidden" name="id" value="${esc(t?.id||'')}"><div class="form-grid"><div class="field full"><label class="label">Navn</label><input class="input" name="name" value="${esc(t?.name||'')}" required></div><div class="field"><label class="label">Ikon</label><input class="input" name="icon" value="${esc(t?.icon||'▧')}" maxlength="4"></div><div class="field full"><label class="label">Beskrivelse</label><textarea class="input" name="description">${esc(t?.description||'')}</textarea></div></div><div class="modal-actions">${t?`<button type="button" class="btn danger" data-action="delete-template" data-template="${t.id}">Slet</button>`:''}<button class="btn primary">Gem</button></div></form>`);
  }
  return '';
}
function modalShell(title,close,body){ return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div class="modal-title">${esc(title)}</div>${close}</div><div class="modal-body">${body}</div></div></div>`; }

